import { Component } from '@angular/core';
import { StaticService } from 'src/app/modules/shared/services/static/static.service';

@Component({
  selector: 'app-test-structure-details',
  templateUrl: './test-structure-details.component.html',
})
export class TestStructureDetailsComponent {
  constructor(public staticService: StaticService) {}
  public fields = {
    'PROPERTY SIZE': [
      'AREA BUILDING (SQ. FT.)',
      'AREA GROSS (SQ. FT.)',
      'AREA 1ST FLOOR (SQ. FT.)',
      'AREA 2ND FLOOR (SQ. FT.)',
      'AREA UPPER FLOORS (SQ. FT.)',
      'AREA LOT (ACRES)',
      'AREA LOT (SQ. FT.)',
      'LOT DEPTH (FT.)',
      'LOT WIDTH (FT.)',
      'ATTIC AREA (SQ. FT.)',
      'ATTIC',
      'BASEMENT AREA (SQ. FT.)',
      'BASEMENT AREA FINISHED (SQ. FT.)',
      'BASEMENT AREA UNFINISHED (SQ. FT.)',
      'PARKING GARAGE',
      'PARKING GARAGE AREA (SQ. FT.)',
      'PARKING CARPORT',
      'LPARKING CARPORT AREA (SQ. FT.)',
    ],
    POOL: ['POOL', 'POOL AREA', 'SAUNA'],
    'INTERNAL STRUCTURE INFORMATION': [
      'FOUNDATION',
      'CONSTRUCTION',
      'INTERIOR STRUCTURE',
      'PLUMBING FIXTURES COUNT',
      'CONSTRUCTION FIRE RESISTANCE CLASS',
      'SAFETY FIRE SPRINKLERS',
      'FLOORING MATERIAL PRIMARY',
    ],
    'ESTIMATED PROPERTY VALUE': [
      'ESTIMATED VALUE',
      'ESTIMATED MIN VALUE',
      'ESTIMATED MAX VALUE',
      'VALUATION DATE',
      'CONFIDENCE SCORE',
    ],
    'INTERNAL ROOM INFORMATION': [
      'BATHROOMS COUNT',
      'PARTIAL BATHROOMS COUNT',
      'BEDROOMS COUNT',
      'ROOMS COUNT',
      'STORIES COUNT',
      'UNITS COUNT',
      'BONUS ROOM',
      'BREAKFAST NOOK',
      'CELLAR',
      'WINE CELLAR',
      'EXERCISE ROOM',
      'FAMILY ROOM',
      'GAME ROOM',
      'GREAT ROOM',
      'HOBBY ROOM',
      'LAUNDRY ROOM',
      'MEDIA ROOM',
      'MUD ROOM',
      'OFFICE AREA',
      'OFFICE',
      'SAFE ROOM',
      'SITTING ROOM',
      'STORM SHELTER',
      'STUDY',
      'SUNROOM',
      'UTILITY AREA',
      'UTILITY ROOM',
    ],
    'INTERNAL AMENITIES': [
      'FIREPLACE',
      'FIREPLACE COUNT',
      'ACCESSABILITY ELEVATOR',
      'ACCESSABILITY HANDICAP',
      'ESCALATOR',
      'CENTRAL VACUUM',
      'INTERCOM',
      'SOUND SYSTEM',
      'WET BAR',
      'SECURITY ALARM',
    ],
    'EXTERNAL STRUCTURE INFORMATION': [
      'EXTERIOR 1 CODE',
      'ROOF MATERIAL',
      'ROOF CONSTRUCTION',
      'STORM SHUTTER',
      'OVERHEAD DOOR',
      'STRUCTURE STYLE',
    ],
    'EXTERNAL AMENITIES': [
      'VIEW DESCRIPTION',
      'PORCH CODE',
      'PORCH AREA (SQ. FT.)',
      'PATIO AREA (SQ. FT.)',
      'DECK',
      'DECK AREA (SQ. FT.)',
      'BALCONY',
      'BALCONY AREA (SQ. FT.)',
      'BREEZEWAY',
    ],
    'EXTERNAL BUILDINGS': [
      'BUILDINGS COUNT',
      'BATH HOUSE AREA (SQ. FT.)',
      'BATH HOUSE',
      'BOAT ACCESS',
      'BOAT HOUSE AREA (SQ. FT.)',
      'BOAT HOUSE',
      'CABIN AREA (SQ. FT.)',
      'CABIN',
      'CANOPY AREA (SQ. FT.)',
      'CANOPY',
      'GAZEBO AREA (SQ. FT.)',
      'GAZEBO',
      'GRANARY AREA (SQ. FT.)',
      'GRANARY',
      'GREEN HOUSE AREA (SQ. FT.)',
      'GREEN HOUSE',
      'GUEST HOUSE AREA (SQ. FT.)',
      'GUEST HOUSE',
      'KENNEL AREA (SQ. FT.)',
      'KENNEL',
      'LEAN-TO AREA (SQ. FT.)',
      'LEAN-TO',
      'LOADING PLATFORM AREA (SQ. FT.)',
      'LOADING PLATFORM',
      'MILK HOUSE AREA (SQ. FT.)',
      'MILK HOUSE',
      'OUTDOOR KITCHEN FIREPLACE',
      'POOL HOUSE AREA (SQ. FT.)',
      'POOL HOUSE',
      'POULTRY HOUSE AREA (SQ. FT.)',
      'POULTRY HOUSE',
      'QUONSET AREA (SQ. FT.)',
      'QUONSET',
      'GSHED AREA (SQ. FT.)',
      'SHED',
      'SILO AREA (SQ. FT.)',
      'STABLE AREA (SQ. FT.)',
      'STABLE',
      'STORAGE BUILDING AREA (SQ. FT.)',
      'STORAGE BUILDING',
      'UTILITY BUILDING AREA (SQ. FT.)',
      'LUTILITY BUILDING',
      'POLE STRUCTURE AREA (SQ. FT.)',
      'POLE STRUCTURE',
    ],
    UTILITIES: [
      'HVAC COOLING DETAIL',
      'HVAC HEATING DETAIL',
      'HVAC HEATING FUEL',
      'SEWAGE USAGE',
      'WATER SOURCE',
      'MOBILE HOME HOOKUP',
    ],
    PARKING: [
      'RV PARKING',
      'PARKING SPACE COUNT',
      'DRIVEWAY AREA',
      'DRIVEWAY MATERIAL',
    ],
    'YARD GARDEN INFORMATION': [
      'TOPOGRAPHY CODE',
      'FENCE CODE',
      'FENCE AREA',
      'COURTYARD',
      'COURTYARD AREA',
      'ARBOR PERGOLA',
      'SPRINKLERS',
      'GOLF COURSE GREEN',
      'TENNIS COURT',
      'SPORTS COURT',
      'ARENA',
      'WATER FEATURE',
      'POND',
      'BOAT LIFT',
    ],
  };
}
